EMPLOYMENT = "emplois"
FILTER_MAIL = "alert@indeed.com"
USER_NAME= "admin"
USER_PASSWORD="admin@123#"
TOKEN="eyJleHAiOjE2NzMyNjgyNjksImlhdCI6MTY2NzIyMDI2OSwic3ViIjoidmFsaWQgdG9rZW4ifQ.UeeVmL5S2kyHVW7wfUw9kuEpUnWMgaCBxCo_YiO7BnI"